# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: afunTW's blog
subtitle: 知世故而不世故，才是最善良的成熟
description: 'Valar Morghulis'
keywords: blog
author: afunTW
language: zh-tw
timezone: Asia/Taipei

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://afuntw.github.io/blog
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: '    '

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: custom
theme_config:
  # Core
  scheme: Muse
  reminder: true
  minfy: true
  # Information Settings
  favicon:
    small: /images/favicon.ico
    medium: /images/favicon.ico
  creative_commons:
    sidebar: true
  darkmode: true
  # Menu
  menu:
    home: / || fa fa-home
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    tags: /tags/ || fa fa-tags
  menu_settings:
    badges: true
  # Sidebar Settings
  sidebar:
    position: left
    # display: always
  avatar:
    url: /images/avatar.jpg
    rounded: true
  social_icons:
    icons_only: true
    transition: true
  toc:
    wrap: true
  # Post Setting
  tag_icon: true
  related_posts:
    enable: true
    display_in_home: true
  # MISC Theme Setting
  codeblock:
    highlight_theme: night eighties
    copy_button:
      enable: true
      show_result: true
  back2top:
    scrollpercent: true
  reading_progress:
    enable: true
  github_banner:
    enable: true
    permalink: https://github.com/afunTW
  # SEO Settings
  exturl: true
  # Third Party Plugins Settings
  math:
    mathjax:
      enable: true
  mediumzoom: true
  lazyload: true
  mermaid:
    enable: true
    theme: dark
  pangu: true
  quicklink:
    enable: true
    home: true
    archive: true
  # Statistics and Analytics
  google_analytics:
    tracking_id: UA-112475986-1

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:
      github: git@github.com:afunTW/afunTW.github.io.git
  branch: master
